### ISSUE TITLE
Monsters Can Pick Up Items

### ISSUE THREAD

**Issue by vanhornchadm** [Zippybing/CS4096-GroupG#7]
Do we want this, or is it a bug?

**Comment by CRDWYB** [comment]
In our discussion today, we considered possible interaction with Monsters and Items, but concluded that the best general solution was that if a Monster moves onto a Tile with an Item, the Monster advances to that tile and the Item is placed on the Tile that the Monster just came from. If some Item could interact with the Monster in a different way, it would still be simple to implement some special logic for that.
