### ISSUE TITLE
Collision With Monster Causes Crash

### ISSUE THREAD

**Issue by VTOL-wins** [Zippybing/CS4096-GroupG#8]
Upon occupying the same tile as the monster any attempt to continue to move throughout the world grid produces a crash with the following error output in console.

Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main()
  File "main.py", line 54, in main
    game.world.moveEntity(game.monster.x,game.monster.y,game.monster.x+xRand,game.monster.y+yRand,None)
  File "/Users/NathanA/Work/CS4096-GroupG/WorldGrid.py", line 66, in moveEntity
    agent.x = x2
AttributeError: 'NoneType' object has no attribute 'x'

**Comment by CRDWYB** [comment]
Once the Hero collides with the Monster or vice versa. The level will have to be reset. This is something that has not been implemented yet, however your crash is a result of the collision where the Monster kills the Hero. While this is currently a problem, once level resetting is in, there will be no option to move the Hero after death.

**Comment by VTOL-wins** [comment]
Understood. I just wanted to put this out there so we had a tracking of the issue until it is implemented properly.
